name: Build and Test Spring Boot Application

# Trigger the workflow on pushes to the main branch and pull requests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

# Define the jobs
jobs:
  build:
    # Run on the latest Ubuntu image
    runs-on: windows-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      # Step 4: Build the application
      - name: Build with Maven
        run: mvn clean install --no-transfer-progress

      # Step 5: Run tests
      - name: Run tests
        run: mvn test --no-transfer-progress
